name: Deploy my Lambda function

on: 
  push:
    branches:
      - main

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: setup python on runner
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install linting libraries
        run: |
          cd function
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: setup python on runner
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: zipped-bundle
      - name: configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://acloud-test-github-actions/${{ github.sha }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: update function code
        run: |
          aws lambda update-function-code \
            --function-name my-function-github-actions \
            --s3-bucket acloud-test-github-actions \
            --s3-key ${{ github.sha }}.zip \
            --publish
      
         
         
          
        
      
